media:
  input: src/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: page
    label: "Page"
    type: collection
    path: 'src/pages'
    fields:
      - name: title
        label: "Page Title"
        type: text
        required: true
      - name: hero
        label: "Hero Section"
        component: hero
      - name: blocks
        label: "Page Blocks"
        type: block
        list: true
        blocks:
          - name: "feature"
            label: Add feature block
            component: featureList
          - name: "testimonial"
            label: Add testimonial block
            component: testimonial
components:
  hero:
    label: "Hero Section"
    type: object
    fields:
      - name: headline
        label: "Headline"
        type: text
        required: true
      - name: subheadline
        label: "Sub-headline"
        type: text
      - name: coverImage
        label: "Cover Image"
        type: image
      - name: callToAction
        label: "Call To Action"
        type: object
        fields:
          - name: label
            label: "Button Label"
            type: text
          - name: url
            label: "Button URL"
            type: string

  testimonial:
    label: "Testimonial"
    type: object
    fields:
      - name: quote
        label: "Quote"
        type: text
      - name: authorName
        label: "Author Name"
        type: text
      - name: authorRole
        label: "Author Role"
        type: text
      - name: authorImage
        label: "Author Image"
        type: image

  featureItem:
    label: "Feature Item"
    type: object
    fields:
      - name: icon
        label: "Icon"
        type: image
      - name: title
        label: "Title"
        type: text
        required: true
      - name: description
        label: "Description"
        type: text
      - name: link
        label: "Learn More Link"
        type: string

  featureList:
    label: "Feature List"
    type: object
    fields:
      - name: features
        label: "Features"
        component: featureItem
        list: true

  faqItem:
    label: "FAQ Item"
    type: object
    fields:
      - name: question
        label: "Question"
        type: text
        required: true
      - name: answer
        label: "Answer"
        type: rich-text

  faqSection:
    label: "FAQ Section"
    type: object
    fields:
      - name: heading
        label: "Heading"
        type: text
      - name: items
        label: "Items"
        component: faqItem
        list: true

  newsletterSignup:
    label: "Newsletter Signup"
    type: object
    fields:
      - name: title
        label: "Title"
        type: text
      - name: description
        label: "Description"
        type: text
      - name: placeholderEmail
        label: "Email Placeholder"
        type: text
      - name: submitLabel
        label: "Submit Button Label"
        type: text
      - name: privacyNotice
        label: "Privacy Notice Text"
        type: text